spring.application.name=ep2-backend-devops
server.port=${SERVER_PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/pacientes?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:pacientes_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:pacientes_pass}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

springdoc.swagger-ui.path=/swagger-ui.html
